global:
  aws:
    enabled: true
    account: "707767160287"
    hatchery_role: "arn:aws:iam::707767160287:role/gen3-service/gen3-testv06-default-hatchery-sa"
    secretStoreServiceAccount:
      enabled: true
      name: external-secrets
      roleArn: "arn:aws:iam::707767160287:role/gen3_service/gen3-testv06-default-external-secrets-sa"
    wafv2:
      enabled: true
      wafAclArn: ""
  dev: false
  externalSecrets:
    deploy: true
  postgres:
    dbCreate: true
    externalSecret: "gen3-testv06-aurora-master-password"
  environment: "gen3-testv06"
  hostname: "test.planx-pla.net"
  revproxyArn: "arn:aws:acm:us-east-1:707767160287:certificate/520ede2f-fc82-4bb9-af96-4b4af7deabbd"
  dictionaryUrl: "https://s3.amazonaws.com/dictionary-artifacts/datadictionary/develop/schema.json"
  portalApp: gitops
  publicDataSets: false
  tierAccessLevel: "private"
  tierAccessLimit: "100"
  netPolicy:
    enabled: false
  dispatcherJobNum: "10"
  frontendRoot: "portal"
  ddEnabled: false

ambassador:
  enabled: true

arborist:
  enabled: true
  externalSecrets:
    dbcreds: "gen3-testv06-default-arborist-creds"

argo-wrapper:
  enabled: false

audit:
  enabled: true
  serviceAccount:
    annotations: 
      eks.amazonaws.com/role-arn: "arn:aws:iam::707767160287:role/gen3_service/gen3-testv06-default-audit-sa"
  externalSecrets:
    dbcreds: "gen3-testv06-default-audit-creds"
    createK8sAuditSecret: true


aws-es-proxy:
  enabled: true
  esEndpoint: "vpc-gen3-testv06-gen3-metadata-adv4yyot3jql6h4fdxznok4ks4.us-east-1.es.amazonaws.com"
  externalSecrets:
    awsCreds: "gen3-testv06-default-aws-es-proxy-creds"

dicom-server:
  enabled: false
  externalSecrets:
    dbcreds: "gen3-testv06-default-dicom-server-creds"

dicom-viewer:
  enabled: false
  externalSecrets:
    dbcreds: "gen3-testv06-default-dicom-viewer-creds"


fence:
  enabled: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::707767160287:role/gen3_service/gen3-testv06-default-fence-sa"

  externalSecrets:
    fenceJwtKeys: "gen3-testv06-default-fence-jwt-keys"
    fenceConfig: "gen3-testv06-default-fence-config"
    fenceGoogleAppCredsSecret: ""
    fenceGoogleStorageCredsSecret: ""
    createK8sGoogleAppSecrets: true
    dbcreds: "gen3-testv06-default-fence-creds"

  usersync:
    usersync: true
    schedule: "*/30 * * * *"
    syncFromDbgap: false
    userYamlS3Path: "s3://cdis-gen3-testv06-users/dev/user.yaml"
    slack_webhook: ""
    slack_send_dbgap: false

frontend-framework:
  enabled: false
  image:
    repository: "quay.io/cdis/frontend-framework"
    tag: "main"

grafana:
  enabled: false

guppy:
  enabled: false

hatchery:
  enabled: true

  hatchery:
    sidecarContainer:
      cpu-limit: '0.1'
      memory-limit: 256Mi
      image: quay.io/cdis/ecs-ws-sidecar:master
      env:
        NAMESPACE: "{{ .Release.Namespace }}"
        HOSTNAME: "{{ .Values.global.hostname }}"
      args: []
      command:
      - "/bin/bash"
      - "./sidecar.sh"
      lifecycle-pre-stop:
      - su
      - "-c"
      - echo test
      - "-s"
      - "/bin/sh"
      - root
    containers:
      -
        target-port: 8888
        cpu-limit: '1.0'
        memory-limit: 2Gi
        name: "(Tutorials) Example Analysis Jupyter Lab Notebooks"
        image: quay.io/cdis/heal-notebooks:combined_tutorials__latest
        env:
          FRAME_ANCESTORS: https://{{ .Values.global.hostname }}
        args:
        - "--NotebookApp.base_url=/lw-workspace/proxy/"
        - "--NotebookApp.default_url=/lab"
        - "--NotebookApp.password=''" #pragma: allowlist secret
        - "--NotebookApp.token=''"
        - "--NotebookApp.shutdown_no_activity_timeout=5400"
        - "--NotebookApp.quit_button=False"
        command:
        - start-notebook.sh
        path-rewrite: "/lw-workspace/proxy/"
        use-tls: 'false'
        ready-probe: "/lw-workspace/proxy/"
        lifecycle-post-start:
        - "/bin/sh"
        - "-c"
        - export IAM=`whoami`; rm -rf /home/$IAM/pd/dockerHome; rm -rf /home/$IAM/pd/lost+found;
          ln -s /data /home/$IAM/pd/; true
        user-uid: 1000
        fs-gid: 100
        user-volume-location: "/home/jovyan/pd"
        gen3-volume-location: "/home/jovyan/.gen3"


indexd:
  enabled: true
  defaultPrefix: "dg.XXXX/"
  externalSecrets:
    dbcreds: "gen3-testv06-default-indexd-creds"
    createK8sServiceCredsSecret: true


manifestservice:
  enabled: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::707767160287:role/gen3_service/gen3-testv06-default-manifestservice-sa"
  externalSecrets:
    createK8sManifestServiceSecret: true

metadata:
  enabled: true
  externalSecrets:
    dbcreds: "gen3-testv06-default-metadata-creds"
    createK8sMetadataSecret: true

peregrine:
  enabled: true
  externalSecrets:
    dbcreds: "gen3-testv06-default-sheepdg-creds"

pidgin:
  enabled: false

portal:
  enabled: true

requestor:
  enabled: false
  externalSecrets:
    dbcreds: "gen3-testv06-default-requestor-creds"

revproxy:
  enabled: true

sheepdog:
  enabled: true
  externalSecrets:
    dbcreds: "gen3-testv06-default-sheepdog-creds"

ssjdispatcher:
  enabled: false

sower:
  enabled: false

wts:
  enabled: true
  externalSecrets:
    dbcreds: "gen3-testv06-default-wts-creds"
    createK8sWtsSecret: true
